source 'https://rubygems.org'

gem 'rom'
gem 'rom-sql'
gem 'rake'
gem 'sqlite3'
gem 'bigdecimal', '1.3.5'


gem "awesome_print", require:"ap"
gem 'pry'

group :test do
  gem 'rack-test'
  gem 'rspec'
end